spring:
  application:
    name: sample-to-devops

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devops_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Chỉ định thẳng cho Hibernate biết luôn: Đây là PostgreSQL, khỏi cần đoán!
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true